// templates.js
// Renders a full HTML page for a private/personal project, using the same
// header/nav/theme-selector/footer markup as the hand-written project pages
// (e.g. autonote.html), with content filled in from projects.json.

function escapeHtml(str) {
    return String(str ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

// Escapes first (so no raw HTML can ever get through), then converts a small,
// safe set of markdown-style inline formatting into real tags:
//   **bold**      -> <strong>bold</strong>
//   *italic*      -> <em>italic</em>
//   _italic_      -> <em>italic</em>
function formatInline(str) {
    return escapeHtml(str)
        .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
        .replace(/(?:\*(.+?)\*|_(.+?)_)/g, (match, a, b) => `<em>${a ?? b}</em>`);
}

function paragraphsToHtml(paragraphs) {
    return (paragraphs || [])
        .filter(p => p && p.trim())
        .map(p => `                <p>\n                    ${formatInline(p.trim())}\n                </p>`)
        .join('\n\n');
}

function techTagsToHtml(tech) {
    return (tech || [])
        .filter(Boolean)
        .map(t => `                <span class="tech-pill">${escapeHtml(t)}</span>`)
        .join('\n');
}

function renderProjectPage(project, slug) {
    const page = project.page || {};

    const title = escapeHtml(project.name);
    const tag = escapeHtml(page.tag || 'Private / Non-Commercial Project');
    const heroDesc = formatInline(page.heroDesc || project.desc || '');
    const aboutTitle = escapeHtml(page.aboutTitle || project.name);
    const aboutParagraphsHtml = paragraphsToHtml(
        page.aboutParagraphs && page.aboutParagraphs.length
            ? page.aboutParagraphs
            : [project.desc || '']
    );
    const techHtml = techTagsToHtml(project.tech);

    const showcaseImg = page.showcaseImg || project.img || '';
    const showcaseCaption = formatInline(page.showcaseCaption || '');

    const ogDesc = escapeHtml(project.desc || '');
    const url = `https://lenadijksma.is-a.dev/${slug}`;

    return `<!-- ${escapeHtml(slug)}.html - auto-generated by the admin panel, do not hand-edit -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>${title} | Lena Dijksma</title>

    <link rel="shortcut icon" href="/images/logo.png" type="image/png">
    <link rel="apple-touch-icon" href="/images/logo.png" sizes="180x180">
    <link rel="manifest" href="/manifest.json">

    <!-- AOS -->
    <link rel="stylesheet" href="/vendor/aos/aos.css" />

    <!-- Remix Icons -->
    <link href="/vendor/remixicon/remixicon.css" rel="stylesheet" />

    <!-- SAME CSS -->
    <link rel="stylesheet" href="/css/style.css" />

    <!-- Extra Meta Tags -->
    <meta name="theme-color" content="${escapeHtml(project.color || '#6fd0f2')}">
    <meta name="robots" content="noindex, follow">

    <!-- Open Graph -->
    <meta property="og:title" content="Lena Dijksma | ${title}" />
    <meta property="og:description" content="${ogDesc}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="${url}" />
    <meta property="og:image" content="https://lenadijksma.is-a.dev/images/og-preview.png" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Lena Dijksma | ${title}" />
    <meta name="twitter:description" content="${ogDesc}" />
    <meta name="twitter:image" content="https://lenadijksma.is-a.dev/images/og-preview.png" />

    <script>
        var savedTheme = localStorage.getItem("theme");
        var prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
        if (savedTheme === "dark" || (!savedTheme && prefersDark)) {
            document.documentElement.classList.add("dark");
        }
        document.documentElement.classList.add("no-transition");
        window.addEventListener("load", () => {
            document.documentElement.classList.remove("no-transition");
        });
    </script>
</head>

<body>
    <div class="background-glow"></div>

    <!-- SAME HEADER -->
    <header class="header">
        <div class="logo">
            <div class="stacked">
                <span>Lena</span>
                <span class="stacked-btm">Dijksma</span>
            </div>
        </div>

        <nav class="nav">
            <a href="/#projects">Back to Portfolio</a>
        </nav>

        <div class="theme-selector">
            <button id="theme-trigger" aria-label="Toggle light/dark mode">
                <i class="ri-moon-line"></i>
            </button>
        </div>

    </header>

    <main>

        <!-- HERO -->
        <section class="hero small-hero">

            <div class="hero-content" data-aos="fade-up">

                <p class="tag-text">
                    ${tag}
                </p>

                <h1 class="page-title">
                    ${title}
                </h1>

                <p class="description">
                    ${heroDesc}
                </p>

                <a href="/#projects" class="primary-btn">
                    Back To Portfolio
                </a>

            </div>

        </section>

        ${techHtml ? `<!-- TECH STACK -->
        <section class="tech-section">

            <div class="section-title" data-aos="fade-up">
                <p>Development</p>
                <h2>Technologies</h2>
            </div>

            <div class="tech-list" data-aos="fade-up">
${techHtml}
            </div>

        </section>` : ''}

        <!-- ABOUT -->
        <section class="about-project-section">

            <div class="about-project-content" data-aos="fade-up">

                <div class="section-title left-align">
                    <p>About</p>
                    <h2>${aboutTitle}</h2>
                </div>

${aboutParagraphsHtml}

            </div>

        </section>

        ${showcaseImg ? `<section class="project-showcase">
            <img src="${escapeHtml(showcaseImg)}" alt="${title} showcase" class="project-image">
            ${showcaseCaption ? `<p class="sub-img-text">${showcaseCaption}</p>` : ''}
        </section>` : ''}

    </main>

    <footer class="footer">
        <p>© ${new Date().getFullYear()} Lena Dijksma</p>
    </footer>

    <!-- AOS -->
    <script src="/vendor/aos/aos.js"></script>

    <script src="/js/main.js"></script>
</body>

</html>
`;
}

module.exports = { renderProjectPage, escapeHtml };
